### ISSUE TITLE
Value JSON support

### ISSUE THREAD

**Issue by jerone** [lazierthanthou/sqlite-manager#12]
I would be great if the value field of type TEXT could add some support for (stringified) JSON. Maybe converting the textbox in the edit record dialog and the tooltips to a treeview.

I'm asking because I'm storing a lot of stringified JSON data in records and reading them isn't easy.

**Comment by landre3567** [comment]
Totally agree.
This is really a Must Have and it does not need a big coding effort

**Comment by jerone** [comment]
In an attempt to clean up my created issues that have not been processed or updated over a year, I'm closing this issue. If this issue is still relevant, please reopen another issue.
