### ISSUE TITLE
Creating Encrypted Database in Sqlite Manager

### ISSUE THREAD

**Issue by Livinlawrence** [lazierthanthou/sqlite-manager#21]
This is not an issue, couldn't find any other place to post this question. I have searched many sites and read a lot of posts but couldn't find the way to create a Encrypted database of using SQLCipher. I do have a database contains thousands of words and I wanted to add this into my Android application. It is stated that Using https://www.zetetic.net/sqlcipher/sqlcipher-for-android/ I can decrypt the encrypted one. Is there any option in this Add on to create/update a database as a Encrypted one.

**Comment by lazierthanthou** [comment]
sqlite engine included in firefox does not support encrypted database
