### ISSUE TITLE
Default value for varchar does not accept space between words.

### ISSUE THREAD

**Issue by Filipizaum** [lazierthanthou/sqlite-manager#26]
SQLiteManager: ALTER TABLE "main"."testtable" ADD COLUMN "testcolumn" VARCHAR DEFAULT foo bar [ near "bar": syntax error ]
Exception Name: NS_ERROR_FAILURE
Exception Message: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [mozIStorageConnection.createStatement]

I think it must identify these kind of situation and surround with double quotes.

**Comment by lazierthanthou** [comment]
the addon only provides gui. Correct syntax needs to be followed.
