### ISSUE TITLE
Provide XUL app package for Firefox

### ISSUE THREAD

**Issue by laurentj** [lazierthanthou/sqlite-manager#31]
[Mozilla plan to deprecate XUL extensions](https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/) : XUL extensions won't work anymore in few month or probably next year in Firefox.

This extension is very useful for me (and many other users I guess). It mustn't died. I see there is an application.ini. So It may work with `firefox --app`. But I didn't find a package dedicated for firefox --app.

To no loose user, I think you should:
- propose a package that it is easy to use with `firefox --app` (probably create a bash/batch file to launch SQlite Manager)
- add this information on your addons.mozilla.org page

**Comment by lazierthanthou** [comment]
The released .zip file with -xr- in the filename, e.g. sqlitemanager-xr-0.8.3-all.zip, is for running as xulrunner app. See https://github.com/lazierthanthou/sqlite-manager/releases. 

Unzip this file and then run firefox -app /path/to/application.ini

Works for me.
