### ISSUE TITLE
Chrome extension won't install

### ISSUE THREAD

**Issue by crollinjones** [lazierthanthou/sqlite-manager#35]
I downloaded the Chrome extension and unzipped the file.  I went to Chrome Extensions, checked Developer Mode and then I click "Load unpacked extensions".  I navigate to the SQLite Manager extension folder and click Ok.  Chrome throws an error “Failed to load extension Manifest file is missing or unreadable.”  I tried saving the chrome.manifest file to UTF8 encoding, same issue.  I am using Chrome 64-bit.

Thank you for your assistance!

**Comment by lazierthanthou** [comment]
addon is for firefox; not chrome
