### ISSUE TITLE
Is this version updated at Mozilla's repos?

### ISSUE THREAD

**Issue by vaibhav-kaushal** [lazierthanthou/sqlite-manager#4]
Hey lazierthanthou (no you are not :stuck_out_tongue: ),

It's not really an issue but since there is no better way to communicate with you, I'm creating one here.

What I wanted to ask is: Is the master branch of this repo sent to Mozilla's Repos? In other words - is this the repo which is updated most? 
The reason I ask is that I am planning to make a firefox extension myself and since this is one of those I admire and use the most, I would like to study the source code of your extension.

**PS [EDIT]**: I can see that the last update was 2 days ago but do you update the code to Mozilla as well?

**Comment by lazierthanthou** [comment]
Well, version 0.8.2 on Mozilla addon site is in sync with commit 4db135a587cef12624d45a4c82d977f16179c349 on github.
