### ISSUE TITLE
Issue with value '15E2621' in column with NUMERIC affinity

### ISSUE THREAD

**Issue by pehachem** [lazierthanthou/sqlite-manager#40]
Using sqlite-manager 0.8.1.1-signed with Firefox 43.0.3 on Windows 8.1, and starting from an empty SQLite file:

CREATE TABLE test (field1 STRING, field2 TEXT);
INSERT INTO test VALUES ('15E2621', '15E2621');

('15E2621' is a serial number that mixes digits and chars)

The value shown in field2 is correct.
The value shown in field1 is 'Infinity', which is not correct

My interpretation:
1 - STRING is not a valid SQLite type, so the 5th rule to chose type affinity applies, and gives NUMERIC.
2 - 15E2621 is parsed successfully as a float... but far too large (infinity).

I have no problem with point 1 (I fixed the issue for myself by changing the column type to TEXT).

/But I have a problem with the behavior of sqlite-manager regarding point 2/: the required reversibility checking (https://www.sqlite.org/datatype3.html, chapter 2) should have invalidate this conversion, leaving the text string, despite the NUMERIC affinity.

**Comment by pehachem** [comment]
I am using sqlite-manager 0.8.3.1 (not 0.8.1.1)
Sorry for the typo...
Hope this helps,
Pehachem

**Comment by lazierthanthou** [comment]
the addon behaves exactly as the sqlite CLI.
