### ISSUE TITLE
Possbility of connection from other SQL lite client?

### ISSUE THREAD

**Issue by ruthan** [lazierthanthou/sqlite-manager#45]
Hello,
i would to know how or have possiblity to connect to Firefox SQLite manager from other SQL client.

 I suppose that is possible export DB file and import it into proper non Firefox SQLite engine, but i would like to connect locally or remotly into SQL lite running in browser engine without any export or db engine installation.

**Comment by lazierthanthou** [comment]
sqlite db lives in a standalone file. Any program that knows to read sqlite files can access the files which you access through this addon.
