### ISSUE TITLE
failed: TypeError: $$(...) is null

### ISSUE THREAD

**Issue by Spitfire4466** [lazierthanthou/sqlite-manager#5]
Since today's update (February 28th), I cannot open nor create any sqlite database using sqlite-manager. Every time I get this error message: Connect to 'Users/Spitfire/.../mydb.sqlite' failed: TypeError: $$(...) is null

**Comment by lazierthanthou** [comment]
Please provide additional info: OS, firefox version and, if possible, a sample db on which the addon fails.

**Comment by Spitfire4466** [comment]
Thank you for your quick answer.

OS X Yosemite 10.10.2
Firefox v36.0
Sample DB: https://www.dropbox.com/s/sri08an625l2ie0/valHerensExcursions.sqlite?dl=0
It's not a DB corruption problem as it is being read fine by one of my python script.

**Comment by lazierthanthou** [comment]
I encountered no issue on Ubuntu 14.04, Firefox 36. Can open as well as create database.

**Comment by Spitfire4466** [comment]
Ok... that's interesting...
I just tested on a Windows 8.1 computer with a fresh SQLite Manager install (never installed before) and firefox 35.0.1 and I get exactly the same issue.
Is there any way I can revert to a previous sqlite manager version?

![screenshot 2015-02-28 19 32 50](https://cloud.githubusercontent.com/assets/6871050/6427442/3f89a132-bf81-11e4-85e9-9246bda126a4.png)

**Comment by lazierthanthou** [comment]
The problem seems to be due to some missing strings in french locale. Please try release at https://github.com/lazierthanthou/sqlite-manager/releases/download/v0.8.3/sqlitemanager-0.8.3-all.xpi and let me know. If it works, I will update on mozilla addon website too.

**Comment by Spitfire4466** [comment]
Working fine now, thanks a lot for the quick fix!
![capture](https://cloud.githubusercontent.com/assets/6871050/6428251/0c72372c-bf9b-11e4-8e88-f5da1f8a62b6.png)

My bad for not reporting I was using the french version... sorry

**Comment by lazierthanthou** [comment]
fixed issue #5 in commit 33dec565aa8632174d46230ea1c3b4985026da1f .
Release v0.8.3 incorporates this fix.
