### ISSUE TITLE
Can't find list of tables

### ISSUE THREAD

**Issue by BrianARice** [lazierthanthou/sqlite-manager#54]
On the left, there has always been a list of the tables that are in the currently opened database.

I must have closed something, because it's not there anymore... and I can't figure out how to reopen it.

Any help?

Thanks - Brian

**Comment by poe101** [comment]
Same problem, I closed the sidebar and now cannot find how to open it. This means I cannot access a table to edit a record manually.

**Comment by lazierthanthou** [comment]
The solution is in the previous comment.
