### ISSUE TITLE
Unable to install add-on

### ISSUE THREAD

**Issue by weltermic** [lazierthanthou/sqlite-manager#59]
When I try to install this add-on, it tells me that it will be installed when Firefox restarts. I click the Restart button, and when Firefox restarts, it takes me back to the install page, but the add-on doesn't install. Any idea why?

**Comment by victorwestmann** [comment]
Have you tried checking your Firefox version? What is your operating system?
Maybe it is already installed. Who knows. Press alt on the keyboard and then go to Tools. It could already be there. (it happened to me!)

**Comment by lazierthanthou** [comment]
The previous comment addresses the issue.
