### ISSUE TITLE
Cannot Import CSV into SQLite Table

### ISSUE THREAD

**Issue by agogomei01** [lazierthanthou/sqlite-manager#6]
Hi support team,

I tried to import an CSV file into an existing Tables but failed.
Error Information:
Exception Name: NS_ERROR_FAILURE
Exception Message: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [mozIStorageConnection.createStatement]

The same csv can create a new tables.

I have no idea anything I miss,
my firefox version is 34.0

Thanks,

aogogmei

**Comment by thadk** [comment]
Try to download the latest version just released in the last couple days and restart your firefox. This Firefox 35 issue should now be resolved (it is for me). Thanks @lazierthanthou!

**Comment by zuphilip** [comment]
I don't think that is the same issue we are seeing here or a consequence of the fix, especially because the csv import into a new table works.

**Comment by zuphilip** [comment]
@agogomei01 Please check that the column names in the table in your database and the first line in the csv file containing the column names match exactly.
