### ISSUE TITLE
this.treeBox is null error on Firefox 53

### ISSUE THREAD

**Issue by mhammond** [lazierthanthou/sqlite-manager#66]
on current nightly the following error is being shown in the console after opening a database:

TypeError: this.treeBox is null[Learn More]  treeDbStructure.js:150:9
	TreeDbStructure.prototype.toggleOpenState chrome://sqlitemanager/content/treeDbStructure.js:150:9
	TreeDbStructure.prototype.setChildData chrome://sqlitemanager/content/treeDbStructure.js:55:13
	SQLiteManager.refreshDbStructure chrome://sqlitemanager/content/sqlitemanager.js:488:5
	SQLiteManager.refresh chrome://sqlitemanager/content/sqlitemanager.js:430:5
	SQLiteManager.useExtensionManagementTable chrome://sqlitemanager/content/sqlitemanager.js:1222:5
	SQLiteManager.setDatabase chrome://sqlitemanager/content/sqlitemanager.js:2519:7
	SQLiteManager.openDatabase chrome://sqlitemanager/content/sqlitemanager.js:1564:9
	oncommand chrome://sqlitemanager/content/sqlitemanager.xul:1:1

Nightlies from a few weeks ago worked (even with e10s enabled)

**Comment by kitcambridge** [comment]
Mine doesn't even get that far; I see `SyntaxError: missing ( after for` in the browser console, pointing to [this line](https://github.com/lazierthanthou/sqlite-manager/blob/33dec565aa8632174d46230ea1c3b4985026da1f/sqlite-manager/chrome/resource/fileIO.js#L22). It looks like the `for each...in` syntax was [recently disabled](https://bugzilla.mozilla.org/show_bug.cgi?id=1293305) in Nightly.
