### ISSUE TITLE
CSV file missing closing double-quote

### ISSUE THREAD

**Issue by randyl** [lazierthanthou/sqlite-manager#68]
When I run the following SQL:

`select 1, 'foo', 'sample text "in quotes"'`

And save it as a CSV file, the file contains the following:

`"1","foo","sample text ""in quotes""`

There should be a third double-quote at the end, to close the quote just before the word sample.

I'm using SQLite Manager 0.8.3.1 on Firefox 50.0.2.

**Comment by lazierthanthou** [comment]
fixed by the commit 28025932587517be66508d37645ab710805b5d69
