### ISSUE TITLE
backwards text in sql db

### ISSUE THREAD

**Issue by iccor56** [lazierthanthou/sqlite-manager#74]
question. when i look at the webappstore.sqlite in this addon i see the origin key and scope contains the url but in reverse text. is there a reason for this and is there a way to fix it so i see the addresses as they are normally?
![1755ba9a43e619ab5eabb9167e3840ee6cda64a9](https://cloud.githubusercontent.com/assets/11468128/23133960/fff1e772-f760-11e6-91e5-1523aa146462.jpg)

**Comment by lazierthanthou** [comment]
this is not an addon issue
