### ISSUE TITLE
Not working FF55 (Nightly)

### ISSUE THREAD

**Issue by scheinercc** [lazierthanthou/sqlite-manager#76]
Firefox SQLs don't get displayed/loaded at all; "Select Profile Database" is empty; manual opening doesn't work either;
Tried "Form History Control" before, same issue.
It's working fine in Dev Edition 54.0a2 (2017-03-14) (64-bit). All Mac OS 10.11

**Comment by lazierthanthou** [comment]
No such problem with FF 54 on Mac OS 10.12
