### ISSUE TITLE
Hi i get this error why ?

### ISSUE THREAD

**Issue by Itachi101** [lazierthanthou/sqlite-manager#77]
SQLiteManager: Error in opening file tutua.pvr.ccz - either the file is encrypted or corrupt
Exception Name: NS_ERROR_FILE_CORRUPTED
Exception Message: Component returned failure code: 0x8052000b (NS_ERROR_FILE_CORRUPTED) [mozIStorageService.openUnsharedDatabase]

**Comment by victorwestmann** [comment]
Can you please clarify when did this happen? What command where you running? What is you Firefox and Operating system version?

**Comment by lazierthanthou** [comment]
reasons could be: encrypted sqlite file or old version of sqlite or not a sqlite file
