### ISSUE TITLE
incompatible with new web extensions / multiprocess firefox

### ISSUE THREAD

**Issue by Pomax** [lazierthanthou/sqlite-manager#81]
With the new multiprocess Firefox, this addon no longer works.

![screenshot 222](https://user-images.githubusercontent.com/177243/28223874-e49d4826-6881-11e7-82a5-3c36d51059db.png)

**Comment by grahamperrin** [comment]
Duplicate of [Migrate to WebExtensions, if it's possible. · Issue #75 · lazierthanthou/sqlite-manager](https://github.com/lazierthanthou/sqlite-manager/issues/75)
