### ISSUE TITLE
Hi,have you decided to upgrade to firefox Quantum?

### ISSUE THREAD

**Issue by Anda001** [lazierthanthou/sqlite-manager#94]
as the firefox upgraded, the plugin no longer to be suited,we need a upgrade

**Comment by justinclift** [comment]
Hi @wuzhenda, this has already been asked several times. #75 #90 #91 #92 

There isn't any good way to upgrade this for Firefox Quantum.  You'll need to find an alternative instead.

My recomendation is https://sqlitebrowser.org, as I am one of the developers for that project.  There are many other alternatives though, if you want something else. :smile:

**Comment by Anda001** [comment]
thanks for replying. I'm not looking for a sqlite tools,but just an easy way to read some sqlite file temply at certain time.
and I  think this one is good 
http://sqliteviewer.flowsoft7.com/

**Comment by justinclift** [comment]
Cool.  Whatever works. :smile:
